### ISSUE TITLE
Couldn't reproduce the results reported in D4RL

### ISSUE THREAD

**Issue by ruizhaogit** [aviralkumar2907/BEAR#5]
Hi @aviralkumar2907 

Thank you for the code!
I try to reproduce the results reported in D4RL "walker2d-medium-v0" environment.
I run the code with the following command:
"python main.py --eval_freq=1000 --algo_name=BEAR --env_name=walker2d-medium-v0 --log_dir=data_walker_BEAR/ --lagrange_thresh=10.0 --distance_type=MMD --mode=auto --num_samples_match=5 --lamda=0.0 --version=0 --mmd_sigma=20.0 --kernel_type=gaussian --use_ensemble_variance="False""

The results are averaged over four random seeds, which are shown here:
![data_walker_BEAR](https://user-images.githubusercontent.com/18663623/81503907-7e75bc80-92e6-11ea-901b-e4f6c0ad00c8.png)

However, the score looks much lower than the reported score 1526.7 in walker2d-medium-v0 D4RL paper.

Do you know how to solve this?

Thank you!

Best,
Rui

**Comment by aviralkumar2907** [comment]
Discussed this over email, so closing this for now.
