### ISSUE TITLE
Couldn't reproduce the result on Mujoco suite.

### ISSUE THREAD

**Issue by sweetice** [aviralkumar2907/BEAR#6]
Couldn't reproduce the result on the Mujoco suite.
Setting: We run the BEAR with the recommend settings: **    `mmd_sigma = 20.0
    `, `kernel_type = gaussian
    `, `num_samples_match = 5
    `, `version = 0 or 2
    `, `lagrange_thresh = 10.0
    `, `mode = auto**
The batch dataset  is produced by training a DDPG agent for 1 million time steps. For reproducing, we use the DDPG code in [BCQ repository](https://github.com/sfujim/BCQ/blob/master/continuous_BCQ/DDPG.py).

We utilize the final buffer setting in [BCQ paper](https://arxiv.org/abs/1812.02900).
Here are the whole results.
Note that the "behavioral" means the evaluation of the DDPG agent when training.

Sweetice 0720 update: Upload the png file for easily reading.
![Ant-v2](https://user-images.githubusercontent.com/17249055/87893088-67cfac80-ca71-11ea-80d5-778312ecf85b.png)
![HalfCheetah-v2](https://user-images.githubusercontent.com/17249055/87893091-6aca9d00-ca71-11ea-9579-9f1ed1ef8377.png)
![Hopper-v2](https://user-images.githubusercontent.com/17249055/87893094-6c946080-ca71-11ea-935f-87c1079cfb41.png)
![InvertedDoublePendulum-v2](https://user-images.githubusercontent.com/17249055/87893096-6dc58d80-ca71-11ea-8d08-0861e18ef437.png)
![InvertedPendulum-v2](https://user-images.githubusercontent.com/17249055/87893097-6e5e2400-ca71-11ea-87c7-832eb5e898cc.png)
![Reacher-v2](https://user-images.githubusercontent.com/17249055/87893101-7027e780-ca71-11ea-8e1b-985bfd9869c6.png)
![Swimmer-v2](https://user-images.githubusercontent.com/17249055/87893102-70c07e00-ca71-11ea-910b-54ae0d69c855.png)
![Walker2d-v2](https://user-images.githubusercontent.com/17249055/87893103-71f1ab00-ca71-11ea-833d-c1e4c061ebe9.png)

For more clear reading.
[Ant-v2.pdf](https://github.com/aviralkumar2907/BEAR/files/4945137/Ant-v2.pdf)
[HalfCheetah-v2.pdf](https://github.com/aviralkumar2907/BEAR/files/4945138/HalfCheetah-v2.pdf)
[Hopper-v2.pdf](https://github.com/aviralkumar2907/BEAR/files/4945139/Hopper-v2.pdf)
[InvertedDoublePendulum-v2.pdf](https://github.com/aviralkumar2907/BEAR/files/4945140/InvertedDoublePendulum-v2.pdf)
[InvertedPendulum-v2.pdf](https://github.com/aviralkumar2907/BEAR/files/4945141/InvertedPendulum-v2.pdf)
[Reacher-v2.pdf](https://github.com/aviralkumar2907/BEAR/files/4945142/Reacher-v2.pdf)
[Swimmer-v2.pdf](https://github.com/aviralkumar2907/BEAR/files/4945143/Swimmer-v2.pdf)
[Walker2d-v2.pdf](https://github.com/aviralkumar2907/BEAR/files/4945144/Walker2d-v2.pdf)

**Comment by aviralkumar2907** [comment]
Hi! In the BEAR paper, we didn't test on the final buffer setting, so I am not sure if the hyperparameters are optimal for this setting as well. I would also recommend trying out the new cleaned up implementation of BEAR, where we have searched over hyperparameters: https://github.com/rail-berkeley/d4rl_evaluations and would also recommend using the D4RL datasets (https://github.com/rail-berkeley/d4rl).
